/*Arduino Pin Numbers*/
#define BACK_LEFT_ENCODER_PIN 21
#define BACK_RIGHT_ENCODER_PIN 20
#define FRONT_LEFT_ENCODER_PIN 19
#define FRONT_RIGHT_ENCODER_PIN 18

#define RANGEFINDER_PIN 6

#define LEFT_MOTOR_PWM_PIN 4
#define RIGHT_MOTOR_PWM_PIN 8
#define LEFT_MOTOR_DIR_PIN 30
#define RIGHT_MOTOR_DIR_PIN 32
#define LEFT_MOTOR_EN_PIN 31
#define RIGHT_MOTOR_EN_PIN 33


#define TILT_SERVO_PIN 9
#define PAN_SERVO_PIN 10

/*Range-finder*/
#define RANGE_RESOLUTION 58//147

/*Encoder Interrupts*/
#define ENCODER_RESOLUTION 1024
#define BACK_LEFT_ENCODER_INT 2
#define BACK_RIGHT_ENCODER_INT 3
#define FRONT_LEFT_ENCODER_INT 4
#define FRONT_RIGHT_ENCODER_INT 5
#define FRONT 0
#define BACK 1

/*DC Motors*/
#define MAX_RPM 10000
#define MOTOR_CCW 0
#define MOTOR_CW 1
#define GEAR_RATIO 54
#define WHEEL_RADIUS 90 //mm
#define DRIVE_SHAFT_RADIUS 200

