/*Arduino Pin Numbers*/
#define BACK_LEFT_ENCODER_PIN 21
#define BACK_RIGHT_ENCODER_PIN 20
#define FRONT_LEFT_ENCODER_PIN 19
#define FRONT_RIGHT_ENCODER_PIN 18

#define BACK_LEFT_ENCODER_DIR_PIN 24
#define BACK_RIGHT_ENCODER_DIR_PIN 25
#define FRONT_LEFT_ENCODER_DIR_PIN 26
#define FRONT_RIGHT_ENCODER_DIR_PIN 27


#define RIGHT 1
#define LEFT 0

#define RANGEFINDER_PIN 4

#define LEFT_MOTOR_PWM_PIN 7
#define RIGHT_MOTOR_PWM_PIN 8
#define LEFT_MOTOR_DIR_PIN 30
#define RIGHT_MOTOR_DIR_PIN 32
#define LEFT_MOTOR_EN_PIN 31
#define RIGHT_MOTOR_EN_PIN 33


#define TILT_SERVO_PIN 9
#define PAN_SERVO_PIN 10

/*Range-finder*/
#define RANGE_RESOLUTION 58//147

/*Encoder Interrupts*/
#define ENCODER_RESOLUTION_FRONT 32
#define ENCODER_RESOLUTION_REAR 2048
#define BACK_LEFT_ENCODER_INT 2
#define BACK_RIGHT_ENCODER_INT 3
#define FRONT_LEFT_ENCODER_INT 4
#define FRONT_RIGHT_ENCODER_INT 5
#define FRONT 0
#define BACK 1

/*DC Motors*/
#define MAX_RPM 10000
#define MOTOR_CCW 0
#define MOTOR_CW 1
#define GEAR_RATIO 70.0//70
#define WHEEL_RADIUS 95.5//93//90 //mm
#define REAR_WHEEL_RADIUS 93.7
#define FRONT_WHEEL_RADIUS 92.95
//back wheels = 93.7
//back right = 95.02
//back left = 93.9
//front 92.95
#define DRIVE_SHAFT_RADIUS 220.0
#define TURN_SCALE 2.2
//420 for back
//x1 33(1/3)in
//y2 7(3/16)in
//x2 (72)(9/16)
//y2 11(1/2)
#define DRIVE_SPEED 300
